<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.3 on win32)" generated="20210208 20:24:15.309" rpa="false">
<suite id="s1" name="LogIn scenario6" source="C:\Users\jttolentino\PycharmProjects\Exam\LogIn\LogIn_scenario6.robot">
<test id="s1-t1" name="Open Website">
<kw name="Open Website" library="Keywords">
<arguments>
<arg>${Website}</arg>
<arg>ie</arg>
</arguments>
<kw name="Open Browser" library="Selenium2Library">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>${URL}</arg>
<arg>${Browser}</arg>
</arguments>
<msg timestamp="20210208 20:24:15.713" level="INFO">Opening browser 'ie' to base url 'https://login.optimyapp.com/'.</msg>
<kw name="Capture Page Screenshot" library="Selenium2Library">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210208 20:29:54.537" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot</msg>
<msg timestamp="20210208 20:29:56.543" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000019015342240&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot</msg>
<msg timestamp="20210208 20:29:58.555" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000019015342198&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot</msg>
<msg timestamp="20210208 20:30:00.720" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51449): Max retries exceeded with url: /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000190153422B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20210208 20:29:39.356" endtime="20210208 20:30:00.720"></status>
</kw>
<msg timestamp="20210208 20:30:00.720" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51449): Max retries exceeded with url: /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000190153422B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<msg timestamp="20210208 20:30:00.744" level="FAIL">TimeoutException: Message: Timed out waiting for page to load.
</msg>
<status status="FAIL" starttime="20210208 20:24:15.713" endtime="20210208 20:30:00.745"></status>
</kw>
<status status="FAIL" starttime="20210208 20:24:15.712" endtime="20210208 20:30:00.745"></status>
</kw>
<status status="FAIL" starttime="20210208 20:24:15.712" endtime="20210208 20:30:00.746" critical="yes">TimeoutException: Message: Timed out waiting for page to load.
</status>
</test>
<doc>This Log in scenario will test the log in page when the user didn't input email upon recovering account</doc>
<status status="FAIL" starttime="20210208 20:24:15.312" endtime="20210208 20:30:00.751"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="LogIn scenario6">LogIn scenario6</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210208 20:29:54.537" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot</msg>
<msg timestamp="20210208 20:29:56.543" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000019015342240&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot</msg>
<msg timestamp="20210208 20:29:58.555" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000019015342198&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot</msg>
<msg timestamp="20210208 20:30:00.720" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51449): Max retries exceeded with url: /session/6496eac6-de2b-4d35-ba40-359218e92baf/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000190153422B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
</errors>
</robot>
